frameworkVersion: "4"

service: serverless-rivet-js

provider:
  name: aws
  runtime: nodejs20.x

functions:
  rivet:
    handler: boot.handler
    events:
      - http:
          path: zoom/events
          method: post

plugins:
  - serverless-offline
  - serverless-dotenv-plugin